# Generated by Django 4.2.5 on 2023-11-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_likedby_post_likedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likedby',
            field=models.ManyToManyField(default=None, related_name='liked_by', to='core.likedby'),
        ),
    ]
