# Generated by Django 4.2.5 on 2023-11-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_post_likedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedby',
            name='user',
        ),
    ]
