# Generated by Django 4.2.5 on 2023-11-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_likedby_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedby',
            name='username',
        ),
    ]
