# Generated by Django 4.2.5 on 2023-11-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_likedby_user_likedby_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likedby',
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
