# Generated by Django 4.2.5 on 2023-11-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_comment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('posted_date', models.DateTimeField()),
            ],
        ),
    ]
