# Generated by Django 5.0.3 on 2024-03-30 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_suicidal'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='toxicity_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='ban_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ban_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_toxic_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_toxicity_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
