# Generated by Django 5.0.3 on 2024-03-30 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_comment_toxicity_status_profile_ban_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_toxic_comment_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post'),
        ),
    ]
